# action.yml
name: 'Yaml Fixer'
description: 'Lint and fix Yaml files'
branding :
  icon : 'file-text'
  color : 'purple'

inputs:
  yaml_file:
    description: "Fichier(s) yaml à tester"
    required: true
  debug:
    description: "Activation du mode debug"
    required: true
    default: false
  verbose:
    description: "Activation du mode verbose"
    required: true
    default: false
  user:
    description: "Compte à utiliser pour la création des pull requests"
    required: false
  token:
    description: "Token pour création des pull requests"
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    YAML_FILE: ${{ inputs.yaml_file }}
    DEBUG: ${{ inputs.debug }}
    VERBOSE: ${{ inputs.verbose }}
    USER: ${{inputs.user}}
    TOKEN: ${{ inputs.token }}
